version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: deutnet_backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: deutnet_frontend
    ports:
      - "80:80"
    depends_on:
      - backend 